name: smetchikapp   # Ð£Ð½Ð¸ÐºÐ°Ð»ÑŒÐ½Ð¾Ðµ Ð½Ð°Ð·Ð²Ð°Ð½Ð¸Ðµ Ð¿Ñ€Ð¾ÐµÐºÑ‚Ð°
description: "Flutter Ð¿Ñ€Ð¸Ð»Ð¾Ð¶ÐµÐ½Ð¸Ðµ Ð´Ð»Ñ ÑÐ¼ÐµÑ‚Ñ‡Ð¸ÐºÐ°"
publish_to: "none"  # Ð£Ð±ÐµÐ¶Ð´Ð°ÐµÐ¼ÑÑ, Ñ‡Ñ‚Ð¾ Ð½Ðµ Ð¿ÑƒÐ±Ð»Ð¸ÐºÑƒÐµÐ¼ Ð² pub.dev

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0  # ÐÐºÑ‚ÑƒÐ°Ð»ÑŒÐ½Ð°Ñ Ð²ÐµÑ€ÑÐ¸Ñ
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2  # Ð•ÑÐ»Ð¸ Ð½ÑƒÐ¶ÐµÐ½ Ð²Ñ…Ð¾Ð´ Ñ‡ÐµÑ€ÐµÐ· Firebase
  firebase_core_platform_interface: ^5.0.0
  image_picker: ^1.0.7  # ÐŸÐ¾ÑÐ»ÐµÐ´Ð½ÑÑ Ð²ÐµÑ€ÑÐ¸Ñ

  http: ^1.3.0
  flutter_markdown: ^0.6.17
  flutter_image: ^4.0.0  # ðŸ“Œ Ð”Ð¾Ð±Ð°Ð²Ð»ÑÐµÐ¼ Ð¿Ð¾Ð´Ð´ÐµÑ€Ð¶ÐºÑƒ Ð·Ð°Ð³Ñ€ÑƒÐ·ÐºÐ¸ Ð¸Ð·Ð¾Ð±Ñ€Ð°Ð¶ÐµÐ½Ð¸Ð¹

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  firebase_data_connect: any
flutter:
  uses-material-design: true
